# Generated by Django 3.2 on 2021-04-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('points', models.IntegerField(default=0, null=True)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
