# Generated by Django 3.2 on 2021-04-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerBoard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board',
            new_name='Players',
        ),
    ]
