# Generated by Django 3.2 on 2021-04-13 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerBoard', '0002_rename_board_players'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Players',
            new_name='Player',
        ),
    ]
