# Generated by Django 3.2 on 2021-04-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerBoard', '0003_rename_players_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='complete',
            new_name='isIn',
        ),
    ]
