# Generated by Django 3.2 on 2021-04-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerBoard', '0004_rename_complete_player_isin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='isIn',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
