# Generated by Django 3.2 on 2021-04-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerBoard', '0005_alter_player_isin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='isIn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
