# Generated by Django 3.2 on 2021-04-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerBoard', '0007_alter_player_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
