# Generated by Django 3.2 on 2021-04-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerBoard', '0009_alter_player_isin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
